### ISSUE TITLE
shuffle has an issue

### ISSUE THREAD

**Issue by Skeeve** [mklauber/tiddly-shuffle#1]
shuffle indeed has an issue, besides that I think randomness of |sin| isn't the best.

Try this tiddler:

```
<ol>
<$list filter="a b c d e f +[shuffle[\x04\x09\x03\x08\x03\x0e]]">
<li><<currentTiddler>></li>
</$list>
</ol>
```

output will be

1. a
2. d
3. e
4. b
5. c
6. 
7. f

This is due to the fact that my random seed-generating-string is carefully crafted so that |sin| will be 1. That way the first shuffle is from array[6] (out of bounds) with array[5] (last index)

There are 28 seeds where this happens:

1. -2015008331
2. -1849301266
3. -1769157409
4. -1603450344
5. -1437743279
6. -1357599422
7. -1191892357
8. -946041435
9. -780334370
10. -700190513
11. -534483448
12. -368776383
13. -288632526
14. -122925461
15. 122925461
16. 288632526
17. 368776383
18. 534483448
19. 700190513
20. 780334370
21. 946041435
22. 1191892357
23. 1357599422
24. 1437743279
25. 1603450344
26. 1769157409
27. 1849301266
28. 2015008331

**Comment by Skeeve** [comment]
One can use this javaScript to generate readable seed-generating strings which specifically create a number one wants:

```
str="";
num=122925461;
while(num>0) {
  r=62+(num % 31);
  str=String.fromCharCode(r) + str;
  num=(num-r)/31;
}
str
```

**Comment by pmario** [comment]
Please have a look here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

**Comment by Skeeve** [comment]
Why, Mario?
