### ISSUE TITLE
shuffle isn't random

### ISSUE THREAD

**Issue by Skeeve** [mklauber/tiddly-shuffle#2]
I calculated for every possible seed the outcome for your "random" generator when doing a "dice roll"

This is the result

Result | Count | Happened | Expected | Difference
-- | -- | -- | -- | --
1 | 457846783 | 10,66 % | 16,67 % | -6,01 %
2 | 471356016 | 10,97 % | 16,67 % | -5,69 %
3 | 502452946 | 11,70 % | 16,67 % | -4,97 %
4 | 563610180 | 13,12 % | 16,67 % | -3,54 %
5 | 698284124 | 16,26 % | 16,67 % | -0,41 %
6 | 1601417219 | 37,29 % | 16,67 % | 20,62 %
7 | 28 | 0,00 % | 0,00 % | 0,00 %

Regarding the 7, please see #1 

But you can clearly see: It's not random as for 4294967296 one would really expect to have each count to be near 715827882.

**Comment by Skeeve** [comment]
If you want something seedable, checkout davidbau.com/archives/2010/01/30/random_seeds_coded_hints_and_quintillions.html

**Comment by mklauber** [comment]
Moved to Math.random for randomness.  Used the https://github.com/davidbau/seedrandom/ for seeding it.
